# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReceitaFederal.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1652, 1158)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color: #f5f5f5;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 1, 0, 0)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_Top = QtWidgets.QFrame(self.centralwidget)
        self.frame_Top.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_Top.setStyleSheet("QFrame{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:0px;\n"
"}")
        self.frame_Top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Top.setObjectName("frame_Top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_Top)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_TopLeft = QtWidgets.QFrame(self.frame_Top)
        self.frame_TopLeft.setMinimumSize(QtCore.QSize(282, 0))
        self.frame_TopLeft.setMaximumSize(QtCore.QSize(282, 16777215))
        self.frame_TopLeft.setStyleSheet("QFrame{\n"
"border:0px;\n"
"\n"
"}")
        self.frame_TopLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TopLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_TopLeft.setObjectName("frame_TopLeft")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_TopLeft)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.pushButton_LogoReceitaFederal = QtWidgets.QPushButton(self.frame_TopLeft)
        self.pushButton_LogoReceitaFederal.setMinimumSize(QtCore.QSize(50, 60))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_LogoReceitaFederal.setFont(font)
        self.pushButton_LogoReceitaFederal.setAutoFillBackground(False)
        self.pushButton_LogoReceitaFederal.setStyleSheet("QPushButton{\n"
"\n"
"color:#1f3b6f;\n"
"font-weight: bold;\n"
"background-color:transparent;\n"
"font-size:26px;\n"
"border:0px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/img/receita-federal 1-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_LogoReceitaFederal.setIcon(icon)
        self.pushButton_LogoReceitaFederal.setIconSize(QtCore.QSize(200, 200))
        self.pushButton_LogoReceitaFederal.setObjectName("pushButton_LogoReceitaFederal")
        self.verticalLayout_21.addWidget(self.pushButton_LogoReceitaFederal)
        self.horizontalLayout.addWidget(self.frame_TopLeft)
        self.frame_TopCenter = QtWidgets.QFrame(self.frame_Top)
        self.frame_TopCenter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TopCenter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_TopCenter.setObjectName("frame_TopCenter")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_TopCenter)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit_TxtTopSearch = QtWidgets.QTextEdit(self.frame_TopCenter)
        self.textEdit_TxtTopSearch.setMinimumSize(QtCore.QSize(242, 0))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.textEdit_TxtTopSearch.setFont(font)
        self.textEdit_TxtTopSearch.setAcceptDrops(False)
        self.textEdit_TxtTopSearch.setToolTip("")
        self.textEdit_TxtTopSearch.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEdit_TxtTopSearch.setStyleSheet("QTextEdit{\n"
"border-radius:15px;\n"
"background-color: #f2f2f2;\n"
"text-align: center;\n"
"font-size:30px;\n"
"color:#8e8e8e;\n"
"}")
        self.textEdit_TxtTopSearch.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textEdit_TxtTopSearch.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_TxtTopSearch.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_TxtTopSearch.setReadOnly(False)
        self.textEdit_TxtTopSearch.setObjectName("textEdit_TxtTopSearch")
        self.horizontalLayout_2.addWidget(self.textEdit_TxtTopSearch)
        self.horizontalLayout.addWidget(self.frame_TopCenter)
        self.frame_TopRight = QtWidgets.QFrame(self.frame_Top)
        self.frame_TopRight.setMinimumSize(QtCore.QSize(350, 0))
        self.frame_TopRight.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_TopRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TopRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_TopRight.setObjectName("frame_TopRight")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_TopRight)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_TopAlert = QtWidgets.QFrame(self.frame_TopRight)
        self.frame_TopAlert.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TopAlert.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_TopAlert.setObjectName("frame_TopAlert")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_TopAlert)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_TopAlert = QtWidgets.QPushButton(self.frame_TopAlert)
        self.pushButton_TopAlert.setStyleSheet("QPushButton{\n"
"color:#1f3b6f;\n"
"font-weight: bold;\n"
"background-color:transparent;\n"
"font-size:15px;\n"
"border:0px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/img/alert.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_TopAlert.setIcon(icon1)
        self.pushButton_TopAlert.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_TopAlert.setObjectName("pushButton_TopAlert")
        self.horizontalLayout_4.addWidget(self.pushButton_TopAlert)
        self.horizontalLayout_3.addWidget(self.frame_TopAlert)
        self.frame_TopProfile = QtWidgets.QFrame(self.frame_TopRight)
        self.frame_TopProfile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TopProfile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_TopProfile.setObjectName("frame_TopProfile")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_TopProfile)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_ImgTopProfile = QtWidgets.QPushButton(self.frame_TopProfile)
        self.pushButton_ImgTopProfile.setStyleSheet("QPushButton{\n"
"color:#1f3b6f;\n"
"font-weight: bold;\n"
"background-color:transparent;\n"
"font-size:15px;\n"
"border:0px;\n"
"}")
        self.pushButton_ImgTopProfile.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/img/profile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ImgTopProfile.setIcon(icon2)
        self.pushButton_ImgTopProfile.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_ImgTopProfile.setObjectName("pushButton_ImgTopProfile")
        self.horizontalLayout_5.addWidget(self.pushButton_ImgTopProfile)
        self.horizontalLayout_3.addWidget(self.frame_TopProfile)
        self.frame_TopDataUser = QtWidgets.QFrame(self.frame_TopRight)
        self.frame_TopDataUser.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_TopDataUser.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TopDataUser.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_TopDataUser.setObjectName("frame_TopDataUser")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_TopDataUser)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_TxtTopDataUser = QtWidgets.QLabel(self.frame_TopDataUser)
        self.label_TxtTopDataUser.setStyleSheet("QLabel{\n"
"\n"
"color:#273142;\n"
"\n"
"}")
        self.label_TxtTopDataUser.setObjectName("label_TxtTopDataUser")
        self.verticalLayout_2.addWidget(self.label_TxtTopDataUser)
        self.label_TxtTopDataUserType = QtWidgets.QLabel(self.frame_TopDataUser)
        self.label_TxtTopDataUserType.setMinimumSize(QtCore.QSize(0, 19))
        self.label_TxtTopDataUserType.setStyleSheet("QLabel{\n"
"color:#9cb2cd;\n"
"}")
        self.label_TxtTopDataUserType.setObjectName("label_TxtTopDataUserType")
        self.verticalLayout_2.addWidget(self.label_TxtTopDataUserType)
        self.horizontalLayout_3.addWidget(self.frame_TopDataUser)
        self.horizontalLayout.addWidget(self.frame_TopRight)
        self.verticalLayout.addWidget(self.frame_Top)
        self.frame_Central = QtWidgets.QFrame(self.centralwidget)
        self.frame_Central.setStyleSheet("QFrame{\n"
"\n"
"    border:0px;\n"
"}")
        self.frame_Central.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Central.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Central.setObjectName("frame_Central")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_Central)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_ColumnLeft = QtWidgets.QFrame(self.frame_Central)
        self.frame_ColumnLeft.setMaximumSize(QtCore.QSize(225, 16777215))
        self.frame_ColumnLeft.setStyleSheet("")
        self.frame_ColumnLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ColumnLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ColumnLeft.setObjectName("frame_ColumnLeft")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_ColumnLeft)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.frame_ColumnLeft)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_BtnDeclarar = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_BtnDeclarar.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_BtnDeclarar.setMaximumSize(QtCore.QSize(234, 50))
        self.pushButton_BtnDeclarar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnDeclarar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BtnDeclarar.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:25px;\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"\n"
"\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assets/img/FAB-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_BtnDeclarar.setIcon(icon3)
        self.pushButton_BtnDeclarar.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_BtnDeclarar.setObjectName("pushButton_BtnDeclarar")
        self.verticalLayout_7.addWidget(self.pushButton_BtnDeclarar)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.frame_7 = QtWidgets.QFrame(self.frame_ColumnLeft)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_BtnServico = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_BtnServico.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_BtnServico.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_BtnServico.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnServico.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BtnServico.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#77a6e7;\n"
"    border:0px;\n"
"    font-size:16px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"")
        self.pushButton_BtnServico.setObjectName("pushButton_BtnServico")
        self.verticalLayout_6.addWidget(self.pushButton_BtnServico)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem)
        self.pushButton_BtnAssuntos = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_BtnAssuntos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnAssuntos.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#77a6e7;\n"
"    border:0px;\n"
"    font-size:16px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"font-weight: bold;\n"
"}")
        self.pushButton_BtnAssuntos.setObjectName("pushButton_BtnAssuntos")
        self.verticalLayout_6.addWidget(self.pushButton_BtnAssuntos)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem1)
        self.pushButton_BtnAcessoInfo = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_BtnAcessoInfo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnAcessoInfo.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#77a6e7;\n"
"    border:0px;\n"
"    font-size:16px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"font-weight: bold;\n"
"}")
        self.pushButton_BtnAcessoInfo.setObjectName("pushButton_BtnAcessoInfo")
        self.verticalLayout_6.addWidget(self.pushButton_BtnAcessoInfo)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem2)
        self.pushButton_BtnComposicao = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_BtnComposicao.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnComposicao.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#77a6e7;\n"
"    border:0px;\n"
"    font-size:16px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"font-weight: bold;\n"
"}")
        self.pushButton_BtnComposicao.setObjectName("pushButton_BtnComposicao")
        self.verticalLayout_6.addWidget(self.pushButton_BtnComposicao)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem3)
        self.pushButton_BtnConsultaProcessos = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_BtnConsultaProcessos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnConsultaProcessos.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#77a6e7;\n"
"    border:0px;\n"
"    font-size:16px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"font-weight: bold;\n"
"}")
        self.pushButton_BtnConsultaProcessos.setObjectName("pushButton_BtnConsultaProcessos")
        self.verticalLayout_6.addWidget(self.pushButton_BtnConsultaProcessos)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem4)
        self.pushButton_BtnCentraisConteudo = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_BtnCentraisConteudo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnCentraisConteudo.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#77a6e7;\n"
"    border:0px;\n"
"    font-size:16px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"font-weight: bold;\n"
"}")
        self.pushButton_BtnCentraisConteudo.setObjectName("pushButton_BtnCentraisConteudo")
        self.verticalLayout_6.addWidget(self.pushButton_BtnCentraisConteudo)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem5)
        self.pushButton_BtnCanaisAtendimento = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_BtnCanaisAtendimento.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnCanaisAtendimento.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#77a6e7;\n"
"    border:0px;\n"
"    font-size:16px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"font-weight: bold;\n"
"}")
        self.pushButton_BtnCanaisAtendimento.setObjectName("pushButton_BtnCanaisAtendimento")
        self.verticalLayout_6.addWidget(self.pushButton_BtnCanaisAtendimento)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem6)
        self.pushButton_BtnOndeEncontro = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_BtnOndeEncontro.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnOndeEncontro.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#77a6e7;\n"
"    border:0px;\n"
"    font-size:16px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"font-weight: bold;\n"
"}")
        self.pushButton_BtnOndeEncontro.setObjectName("pushButton_BtnOndeEncontro")
        self.verticalLayout_6.addWidget(self.pushButton_BtnOndeEncontro)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem7)
        self.pushButton_BtnGovbr = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_BtnGovbr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnGovbr.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#77a6e7;\n"
"    border:0px;\n"
"    font-size:16px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"font-weight: bold;\n"
"}")
        self.pushButton_BtnGovbr.setObjectName("pushButton_BtnGovbr")
        self.verticalLayout_6.addWidget(self.pushButton_BtnGovbr)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.pushButton_BtnConfiguracao = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_BtnConfiguracao.setStyleSheet("QPushButton{\n"
"    text-align:center;\n"
"    color:#acacbf;\n"
"    border:0px;\n"
"    font-size:16px;\n"
"    cursor: pointer;\n"
"    font-style: italic;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("assets/img/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_BtnConfiguracao.setIcon(icon4)
        self.pushButton_BtnConfiguracao.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_BtnConfiguracao.setObjectName("pushButton_BtnConfiguracao")
        self.verticalLayout_6.addWidget(self.pushButton_BtnConfiguracao)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem9)
        self.frame = QtWidgets.QFrame(self.frame_7)
        self.frame.setMinimumSize(QtCore.QSize(0, 2))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 2))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: #e9e9ee;\n"
"    border:0px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6.addWidget(self.frame)
        self.pushButton_BtnFeedback = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_BtnFeedback.setStyleSheet("QPushButton{\n"
"    text-align:center;\n"
"    color:#acacbf;\n"
"    border:0px;\n"
"    font-size:14px;\n"
"    cursor: pointer;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"}")
        self.pushButton_BtnFeedback.setObjectName("pushButton_BtnFeedback")
        self.verticalLayout_6.addWidget(self.pushButton_BtnFeedback)
        self.pushButton_BtnSugestao = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_BtnSugestao.setStyleSheet("QPushButton{\n"
"    text-align:center;\n"
"    color:#acacbf;\n"
"    border:0px;\n"
"    font-size:14px;\n"
"    cursor: pointer;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"}")
        self.pushButton_BtnSugestao.setObjectName("pushButton_BtnSugestao")
        self.verticalLayout_6.addWidget(self.pushButton_BtnSugestao)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem10)
        self.pushButton_ImgLogoGovbr = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_ImgLogoGovbr.setStyleSheet("QPushButton{\n"
"    border:0px;\n"
"}\n"
"    ")
        self.pushButton_ImgLogoGovbr.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("assets/img/Settings-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ImgLogoGovbr.setIcon(icon5)
        self.pushButton_ImgLogoGovbr.setIconSize(QtCore.QSize(300, 60))
        self.pushButton_ImgLogoGovbr.setObjectName("pushButton_ImgLogoGovbr")
        self.verticalLayout_6.addWidget(self.pushButton_ImgLogoGovbr)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.horizontalLayout_6.addWidget(self.frame_ColumnLeft)
        self.frame_ColumnCenter = QtWidgets.QFrame(self.frame_Central)
        self.frame_ColumnCenter.setStyleSheet("")
        self.frame_ColumnCenter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ColumnCenter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ColumnCenter.setObjectName("frame_ColumnCenter")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_ColumnCenter)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_ColumnCenter)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.lineEdit_TxtDataAtual = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_TxtDataAtual.setGeometry(QtCore.QRect(10, 15, 190, 50))
        self.lineEdit_TxtDataAtual.setMinimumSize(QtCore.QSize(190, 50))
        self.lineEdit_TxtDataAtual.setMaximumSize(QtCore.QSize(190, 50))
        self.lineEdit_TxtDataAtual.setStyleSheet("QLineEdit{\n"
"border-radius:15px;\n"
"background-color: #fff;\n"
"text-align: center;\n"
"font-size:15px;\n"
"color:#273142;\n"
"border:1px solid #e1e4ed;\n"
"text-aling:center;\n"
"}")
        self.lineEdit_TxtDataAtual.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_TxtDataAtual.setObjectName("lineEdit_TxtDataAtual")
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame_DashCentral = QtWidgets.QFrame(self.frame_ColumnCenter)
        self.frame_DashCentral.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"border:0px;\n"
"}")
        self.frame_DashCentral.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_DashCentral.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_DashCentral.setObjectName("frame_DashCentral")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_DashCentral)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_2 = QtWidgets.QFrame(self.frame_DashCentral)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_TitleDash = QtWidgets.QLabel(self.frame_2)
        self.label_TitleDash.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_TitleDash.setStyleSheet("QLabel{\n"
"\n"
"color:#010101;\n"
"border:0px;\n"
"font-size:40px;\n"
"font-weight: bold;\n"
"}")
        self.label_TitleDash.setObjectName("label_TitleDash")
        self.verticalLayout_9.addWidget(self.label_TitleDash)
        self.label_SubTitleDash = QtWidgets.QLabel(self.frame_2)
        self.label_SubTitleDash.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_SubTitleDash.setStyleSheet("QLabel{\n"
"\n"
"color:#010101;\n"
"border:0px;\n"
"font-size:15px;\n"
"}")
        self.label_SubTitleDash.setObjectName("label_SubTitleDash")
        self.verticalLayout_9.addWidget(self.label_SubTitleDash)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem11)
        self.verticalLayout_8.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame_DashCentral)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_CPF = QtWidgets.QFrame(self.frame_3)
        self.frame_CPF.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_CPF.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_CPF.setStyleSheet("QFrame{ \n"
"background-color: #f2f2f2;\n"
"\n"
"\n"
" }")
        self.frame_CPF.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CPF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CPF.setObjectName("frame_CPF")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_CPF)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_16 = QtWidgets.QFrame(self.frame_CPF)
        self.frame_16.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_16.setStyleSheet("QFrame{ border:0px }")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_TitleCPF = QtWidgets.QLabel(self.frame_16)
        self.label_TitleCPF.setStyleSheet("QLabel{\n"
"\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:45px;\n"
"font-weight: bold;\n"
"}")
        self.label_TitleCPF.setObjectName("label_TitleCPF")
        self.verticalLayout_10.addWidget(self.label_TitleCPF)
        self.label_SubTitleCPF = QtWidgets.QLabel(self.frame_16)
        self.label_SubTitleCPF.setStyleSheet("\n"
"QLabel{\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:15px;\n"
"}")
        self.label_SubTitleCPF.setObjectName("label_SubTitleCPF")
        self.verticalLayout_10.addWidget(self.label_SubTitleCPF)
        self.pushButton_BtnCPF = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_BtnCPF.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_BtnCPF.setMaximumSize(QtCore.QSize(234, 50))
        self.pushButton_BtnCPF.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnCPF.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BtnCPF.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:25px;\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"\n"
"\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/path395.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_BtnCPF.setIcon(icon6)
        self.pushButton_BtnCPF.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_BtnCPF.setObjectName("pushButton_BtnCPF")
        self.verticalLayout_10.addWidget(self.pushButton_BtnCPF)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem12)
        self.horizontalLayout_9.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.frame_CPF)
        self.frame_17.setStyleSheet("QFrame{ border:0px }")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_ImgCPF = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_ImgCPF.setStyleSheet("QPushButton{ border:0px }")
        self.pushButton_ImgCPF.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/Component 2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ImgCPF.setIcon(icon7)
        self.pushButton_ImgCPF.setIconSize(QtCore.QSize(150, 300))
        self.pushButton_ImgCPF.setObjectName("pushButton_ImgCPF")
        self.horizontalLayout_10.addWidget(self.pushButton_ImgCPF)
        self.horizontalLayout_9.addWidget(self.frame_17)
        self.horizontalLayout_7.addWidget(self.frame_CPF)
        self.frame_Alfandega = QtWidgets.QFrame(self.frame_3)
        self.frame_Alfandega.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_Alfandega.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_Alfandega.setStyleSheet("QFrame{ background-color: #f2f2f2; }")
        self.frame_Alfandega.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Alfandega.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Alfandega.setObjectName("frame_Alfandega")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_Alfandega)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_24 = QtWidgets.QFrame(self.frame_Alfandega)
        self.frame_24.setStyleSheet("QFrame{ border:0px }")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_19 = QtWidgets.QFrame(self.frame_24)
        self.frame_19.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_19.setStyleSheet("QFrame{ border:0px }")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_TitleAlfandega = QtWidgets.QLabel(self.frame_19)
        self.label_TitleAlfandega.setMinimumSize(QtCore.QSize(230, 0))
        self.label_TitleAlfandega.setStyleSheet("QLabel{\n"
"\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:45px;\n"
"font-weight: bold;\n"
"}")
        self.label_TitleAlfandega.setObjectName("label_TitleAlfandega")
        self.verticalLayout_11.addWidget(self.label_TitleAlfandega)
        self.label_SubTitleAlfandega = QtWidgets.QLabel(self.frame_19)
        self.label_SubTitleAlfandega.setStyleSheet("\n"
"QLabel{\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:15px;\n"
"}")
        self.label_SubTitleAlfandega.setObjectName("label_SubTitleAlfandega")
        self.verticalLayout_11.addWidget(self.label_SubTitleAlfandega)
        self.horizontalLayout_11.addWidget(self.frame_19)
        self.pushButton_ImgAlfandega = QtWidgets.QPushButton(self.frame_24)
        self.pushButton_ImgAlfandega.setStyleSheet("QPushButton{ border:0px }")
        self.pushButton_ImgAlfandega.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/img/Flying around the world-rafiki 2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ImgAlfandega.setIcon(icon8)
        self.pushButton_ImgAlfandega.setIconSize(QtCore.QSize(150, 350))
        self.pushButton_ImgAlfandega.setObjectName("pushButton_ImgAlfandega")
        self.horizontalLayout_11.addWidget(self.pushButton_ImgAlfandega)
        self.verticalLayout_14.addWidget(self.frame_24)
        self.frame_23 = QtWidgets.QFrame(self.frame_Alfandega)
        self.frame_23.setStyleSheet("QFrame{ border:0px }")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pushButton_BtnAlfandega = QtWidgets.QPushButton(self.frame_23)
        self.pushButton_BtnAlfandega.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_BtnAlfandega.setMaximumSize(QtCore.QSize(234, 50))
        self.pushButton_BtnAlfandega.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnAlfandega.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BtnAlfandega.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:25px;\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_BtnAlfandega.setIcon(icon6)
        self.pushButton_BtnAlfandega.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_BtnAlfandega.setObjectName("pushButton_BtnAlfandega")
        self.verticalLayout_15.addWidget(self.pushButton_BtnAlfandega)
        self.verticalLayout_14.addWidget(self.frame_23)
        self.horizontalLayout_7.addWidget(self.frame_Alfandega)
        self.verticalLayout_8.addWidget(self.frame_3)
        self.frame_AjusteAnual = QtWidgets.QFrame(self.frame_DashCentral)
        self.frame_AjusteAnual.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_AjusteAnual.setStyleSheet("QFrame{ background-color: #f2f2f2; }")
        self.frame_AjusteAnual.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_AjusteAnual.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_AjusteAnual.setObjectName("frame_AjusteAnual")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_AjusteAnual)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_20 = QtWidgets.QFrame(self.frame_AjusteAnual)
        self.frame_20.setStyleSheet("QFrame{ border:0px }")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_ImgAjusteAnual = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_ImgAjusteAnual.setStyleSheet("QPushButton{ border:0px }")
        self.pushButton_ImgAjusteAnual.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/img/Online-cuate 1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ImgAjusteAnual.setIcon(icon9)
        self.pushButton_ImgAjusteAnual.setIconSize(QtCore.QSize(300, 300))
        self.pushButton_ImgAjusteAnual.setObjectName("pushButton_ImgAjusteAnual")
        self.horizontalLayout_13.addWidget(self.pushButton_ImgAjusteAnual)
        self.horizontalLayout_14.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.frame_AjusteAnual)
        self.frame_21.setStyleSheet("QFrame{ border:0px }")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem13)
        self.label_TitleDeclaracao = QtWidgets.QLabel(self.frame_21)
        self.label_TitleDeclaracao.setStyleSheet("QLabel{\n"
"\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:40px;\n"
"}")
        self.label_TitleDeclaracao.setObjectName("label_TitleDeclaracao")
        self.verticalLayout_12.addWidget(self.label_TitleDeclaracao)
        self.label_SubTitleDeclaracao = QtWidgets.QLabel(self.frame_21)
        self.label_SubTitleDeclaracao.setStyleSheet("\n"
"QLabel{\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:40px;\n"
"font-weight: bold;\n"
"}")
        self.label_SubTitleDeclaracao.setObjectName("label_SubTitleDeclaracao")
        self.verticalLayout_12.addWidget(self.label_SubTitleDeclaracao)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem14)
        self.horizontalLayout_14.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(self.frame_AjusteAnual)
        self.frame_22.setStyleSheet("QFrame{ border:0px }")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.pushButton_BtnAjusteAnual = QtWidgets.QPushButton(self.frame_22)
        self.pushButton_BtnAjusteAnual.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_BtnAjusteAnual.setMaximumSize(QtCore.QSize(234, 50))
        self.pushButton_BtnAjusteAnual.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnAjusteAnual.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BtnAjusteAnual.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:25px;\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_BtnAjusteAnual.setIcon(icon6)
        self.pushButton_BtnAjusteAnual.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_BtnAjusteAnual.setObjectName("pushButton_BtnAjusteAnual")
        self.verticalLayout_13.addWidget(self.pushButton_BtnAjusteAnual)
        self.horizontalLayout_14.addWidget(self.frame_22)
        self.verticalLayout_8.addWidget(self.frame_AjusteAnual)
        self.frame_11 = QtWidgets.QFrame(self.frame_DashCentral)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_ImpostoDeRenda = QtWidgets.QFrame(self.frame_11)
        self.frame_ImpostoDeRenda.setStyleSheet("QFrame{ background-color: #f2f2f2; }")
        self.frame_ImpostoDeRenda.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ImpostoDeRenda.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ImpostoDeRenda.setObjectName("frame_ImpostoDeRenda")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_ImpostoDeRenda)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_18 = QtWidgets.QFrame(self.frame_ImpostoDeRenda)
        self.frame_18.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_18.setStyleSheet("QFrame{ border:0px }")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_TitleImposto = QtWidgets.QLabel(self.frame_18)
        self.label_TitleImposto.setStyleSheet("QLabel{\n"
"\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:35px;\n"
"font-weight: bold;\n"
"}")
        self.label_TitleImposto.setObjectName("label_TitleImposto")
        self.verticalLayout_16.addWidget(self.label_TitleImposto)
        self.label_SubTitleImposto = QtWidgets.QLabel(self.frame_18)
        self.label_SubTitleImposto.setStyleSheet("\n"
"QLabel{\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:25px;\n"
"}")
        self.label_SubTitleImposto.setObjectName("label_SubTitleImposto")
        self.verticalLayout_16.addWidget(self.label_SubTitleImposto)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem15)
        self.pushButton_BtnImpostoRenda = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_BtnImpostoRenda.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_BtnImpostoRenda.setMaximumSize(QtCore.QSize(234, 50))
        self.pushButton_BtnImpostoRenda.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnImpostoRenda.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BtnImpostoRenda.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:20px;\n"
"    font-size:15px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}")
        self.pushButton_BtnImpostoRenda.setIcon(icon6)
        self.pushButton_BtnImpostoRenda.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_BtnImpostoRenda.setObjectName("pushButton_BtnImpostoRenda")
        self.verticalLayout_16.addWidget(self.pushButton_BtnImpostoRenda)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem16)
        self.horizontalLayout_15.addWidget(self.frame_18)
        self.frame_25 = QtWidgets.QFrame(self.frame_ImpostoDeRenda)
        self.frame_25.setStyleSheet("QFrame{ border:0px }")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_ImgImpostoRenda = QtWidgets.QPushButton(self.frame_25)
        self.pushButton_ImgImpostoRenda.setStyleSheet("QPushButton{ border:0px }")
        self.pushButton_ImgImpostoRenda.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/img/Component 4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ImgImpostoRenda.setIcon(icon10)
        self.pushButton_ImgImpostoRenda.setIconSize(QtCore.QSize(180, 180))
        self.pushButton_ImgImpostoRenda.setObjectName("pushButton_ImgImpostoRenda")
        self.horizontalLayout_12.addWidget(self.pushButton_ImgImpostoRenda)
        self.horizontalLayout_15.addWidget(self.frame_25)
        self.horizontalLayout_8.addWidget(self.frame_ImpostoDeRenda)
        self.frame_DeclaracaoImport = QtWidgets.QFrame(self.frame_11)
        self.frame_DeclaracaoImport.setMinimumSize(QtCore.QSize(437, 0))
        self.frame_DeclaracaoImport.setStyleSheet("QFrame{ background-color: #f2f2f2; }")
        self.frame_DeclaracaoImport.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_DeclaracaoImport.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_DeclaracaoImport.setObjectName("frame_DeclaracaoImport")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_DeclaracaoImport)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame_26 = QtWidgets.QFrame(self.frame_DeclaracaoImport)
        self.frame_26.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_26.setStyleSheet("QFrame{ border:0px }")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_11 = QtWidgets.QLabel(self.frame_26)
        self.label_11.setStyleSheet("QLabel{\n"
"\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:35px;\n"
"font-weight: bold;\n"
"}")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_17.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.frame_26)
        self.label_12.setStyleSheet("\n"
"QLabel{\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:25px;\n"
"}")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_17.addWidget(self.label_12)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem17)
        self.pushButton_BtnDeclaracaoImport = QtWidgets.QPushButton(self.frame_26)
        self.pushButton_BtnDeclaracaoImport.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_BtnDeclaracaoImport.setMaximumSize(QtCore.QSize(234, 50))
        self.pushButton_BtnDeclaracaoImport.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnDeclaracaoImport.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BtnDeclaracaoImport.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:20px;\n"
"    font-size:15px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}")
        self.pushButton_BtnDeclaracaoImport.setIcon(icon6)
        self.pushButton_BtnDeclaracaoImport.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_BtnDeclaracaoImport.setObjectName("pushButton_BtnDeclaracaoImport")
        self.verticalLayout_17.addWidget(self.pushButton_BtnDeclaracaoImport)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem18)
        self.horizontalLayout_17.addWidget(self.frame_26)
        self.frame_27 = QtWidgets.QFrame(self.frame_DeclaracaoImport)
        self.frame_27.setStyleSheet("QFrame{ border:0px }")
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_ImgDeclaracaoImport = QtWidgets.QPushButton(self.frame_27)
        self.pushButton_ImgDeclaracaoImport.setStyleSheet("QPushButton{ border:0px }")
        self.pushButton_ImgDeclaracaoImport.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/img/Component 5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ImgDeclaracaoImport.setIcon(icon11)
        self.pushButton_ImgDeclaracaoImport.setIconSize(QtCore.QSize(180, 180))
        self.pushButton_ImgDeclaracaoImport.setObjectName("pushButton_ImgDeclaracaoImport")
        self.horizontalLayout_16.addWidget(self.pushButton_ImgDeclaracaoImport)
        self.horizontalLayout_17.addWidget(self.frame_27)
        self.horizontalLayout_8.addWidget(self.frame_DeclaracaoImport)
        self.verticalLayout_8.addWidget(self.frame_11)
        self.verticalLayout_3.addWidget(self.frame_DashCentral)
        self.horizontalLayout_6.addWidget(self.frame_ColumnCenter)
        self.frame_ColumnRight = QtWidgets.QFrame(self.frame_Central)
        self.frame_ColumnRight.setMaximumSize(QtCore.QSize(473, 16777215))
        self.frame_ColumnRight.setStyleSheet("")
        self.frame_ColumnRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ColumnRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ColumnRight.setObjectName("frame_ColumnRight")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_ColumnRight)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_6 = QtWidgets.QFrame(self.frame_ColumnRight)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Restituicao = QtWidgets.QLabel(self.frame_6)
        self.label_Restituicao.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_Restituicao.setStyleSheet("\n"
"QLabel{\n"
"color:#9cb2cd;\n"
"border:0px;\n"
"font-size:15px;\n"
"}")
        self.label_Restituicao.setObjectName("label_Restituicao")
        self.gridLayout.addWidget(self.label_Restituicao, 0, 0, 1, 1)
        self.label_TxtValorRestituicao = QtWidgets.QLabel(self.frame_6)
        self.label_TxtValorRestituicao.setStyleSheet("\n"
"QLabel{\n"
"color:#273142;\n"
"border:0px;\n"
"font-size:15px;\n"
"}")
        self.label_TxtValorRestituicao.setObjectName("label_TxtValorRestituicao")
        self.gridLayout.addWidget(self.label_TxtValorRestituicao, 0, 1, 1, 1)
        self.pushButton_BtnHistorico = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_BtnHistorico.setMinimumSize(QtCore.QSize(0, 48))
        self.pushButton_BtnHistorico.setMaximumSize(QtCore.QSize(234, 48))
        self.pushButton_BtnHistorico.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnHistorico.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BtnHistorico.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:20px;\n"
"    font-size:15px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}")
        self.pushButton_BtnHistorico.setIcon(icon6)
        self.pushButton_BtnHistorico.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_BtnHistorico.setObjectName("pushButton_BtnHistorico")
        self.gridLayout.addWidget(self.pushButton_BtnHistorico, 0, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_6)
        self.frame_9 = QtWidgets.QFrame(self.frame_ColumnRight)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_CentralAjuda = QtWidgets.QFrame(self.frame_9)
        self.frame_CentralAjuda.setStyleSheet("QFrame{\n"
"\n"
"    border-radius:10px;\n"
"    background-color: #efefef;\n"
"border:0px;\n"
"\n"
"\n"
"}")
        self.frame_CentralAjuda.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CentralAjuda.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CentralAjuda.setObjectName("frame_CentralAjuda")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_CentralAjuda)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_TitleCentralAjuda = QtWidgets.QLabel(self.frame_CentralAjuda)
        self.label_TitleCentralAjuda.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_TitleCentralAjuda.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_TitleCentralAjuda.setStyleSheet("QLabel{\n"
"text-align:center;\n"
"color:#010101;\n"
"border:0px;\n"
"font-size:30px;\n"
"font-weight: bold;\n"
"\n"
"}")
        self.label_TitleCentralAjuda.setTextFormat(QtCore.Qt.PlainText)
        self.label_TitleCentralAjuda.setAlignment(QtCore.Qt.AlignCenter)
        self.label_TitleCentralAjuda.setObjectName("label_TitleCentralAjuda")
        self.verticalLayout_20.addWidget(self.label_TitleCentralAjuda)
        self.pushButton_BtnAjuda01 = QtWidgets.QPushButton(self.frame_CentralAjuda)
        self.pushButton_BtnAjuda01.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_BtnAjuda01.setMaximumSize(QtCore.QSize(16777215, 65))
        self.pushButton_BtnAjuda01.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnAjuda01.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BtnAjuda01.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#585858;\n"
"\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"\n"
"    background-color:transparent;\n"
"    border-radius:0px;\n"
"    border-bottom: 1px solid #acacbf;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#4b6272;\n"
"}")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/img/+-15.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_BtnAjuda01.setIcon(icon12)
        self.pushButton_BtnAjuda01.setIconSize(QtCore.QSize(150, 150))
        self.pushButton_BtnAjuda01.setObjectName("pushButton_BtnAjuda01")
        self.verticalLayout_20.addWidget(self.pushButton_BtnAjuda01)
        self.pushButton_BtnAjuda02 = QtWidgets.QPushButton(self.frame_CentralAjuda)
        self.pushButton_BtnAjuda02.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_BtnAjuda02.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_BtnAjuda02.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnAjuda02.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BtnAjuda02.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#585858;\n"
"\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"\n"
"    background-color:transparent;\n"
"    border-radius:0px;\n"
"    border-bottom: 1px solid #acacbf;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#4b6272;\n"
"}")
        self.pushButton_BtnAjuda02.setIcon(icon12)
        self.pushButton_BtnAjuda02.setIconSize(QtCore.QSize(150, 150))
        self.pushButton_BtnAjuda02.setObjectName("pushButton_BtnAjuda02")
        self.verticalLayout_20.addWidget(self.pushButton_BtnAjuda02)
        self.pushButton_BtnAjuda03 = QtWidgets.QPushButton(self.frame_CentralAjuda)
        self.pushButton_BtnAjuda03.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_BtnAjuda03.setMaximumSize(QtCore.QSize(16777215, 65))
        self.pushButton_BtnAjuda03.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnAjuda03.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BtnAjuda03.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#585858;\n"
"\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"\n"
"    background-color:transparent;\n"
"    border-radius:0px;\n"
"    border-bottom: 1px solid #acacbf;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#4b6272;\n"
"}")
        self.pushButton_BtnAjuda03.setIcon(icon12)
        self.pushButton_BtnAjuda03.setIconSize(QtCore.QSize(150, 150))
        self.pushButton_BtnAjuda03.setObjectName("pushButton_BtnAjuda03")
        self.verticalLayout_20.addWidget(self.pushButton_BtnAjuda03)
        self.pushButton_BtnAjuda04 = QtWidgets.QPushButton(self.frame_CentralAjuda)
        self.pushButton_BtnAjuda04.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_BtnAjuda04.setMaximumSize(QtCore.QSize(16777215, 65))
        self.pushButton_BtnAjuda04.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnAjuda04.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BtnAjuda04.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#585858;\n"
"\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"\n"
"    background-color:transparent;\n"
"    border-radius:0px;\n"
"    border-bottom: 1px solid #acacbf;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#4b6272;\n"
"}")
        self.pushButton_BtnAjuda04.setIcon(icon12)
        self.pushButton_BtnAjuda04.setIconSize(QtCore.QSize(150, 150))
        self.pushButton_BtnAjuda04.setObjectName("pushButton_BtnAjuda04")
        self.verticalLayout_20.addWidget(self.pushButton_BtnAjuda04)
        self.verticalLayout_18.addWidget(self.frame_CentralAjuda)
        self.frame_29 = QtWidgets.QFrame(self.frame_9)
        self.frame_29.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_29.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_29.setStyleSheet("QFrame{\n"
"\n"
"    border-radius:10px;\n"
"    background-color: #efefef;\n"
"border:0px;\n"
"\n"
"\n"
"}")
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_29)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_RestituicaoIR = QtWidgets.QLabel(self.frame_29)
        self.label_RestituicaoIR.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_RestituicaoIR.setStyleSheet("QLabel{\n"
"\n"
"color:#010101;\n"
"border:0px;\n"
"font-size:30px;\n"
"}")
        self.label_RestituicaoIR.setObjectName("label_RestituicaoIR")
        self.gridLayout_2.addWidget(self.label_RestituicaoIR, 0, 0, 1, 1)
        self.pushButton_BtnRestituicaoIR = QtWidgets.QPushButton(self.frame_29)
        self.pushButton_BtnRestituicaoIR.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_BtnRestituicaoIR.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_BtnRestituicaoIR.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnRestituicaoIR.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BtnRestituicaoIR.setStyleSheet("QPushButton{\n"
"    text-align:center;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:35px;\n"
"    font-size:15px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}")
        self.pushButton_BtnRestituicaoIR.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/img/FAB-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_BtnRestituicaoIR.setIcon(icon13)
        self.pushButton_BtnRestituicaoIR.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_BtnRestituicaoIR.setObjectName("pushButton_BtnRestituicaoIR")
        self.gridLayout_2.addWidget(self.pushButton_BtnRestituicaoIR, 0, 1, 1, 1)
        self.verticalLayout_18.addWidget(self.frame_29)
        self.frame_30 = QtWidgets.QFrame(self.frame_9)
        self.frame_30.setStyleSheet("QFrame{ border:0px; }")
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_TitleAjudaLEO = QtWidgets.QLabel(self.frame_30)
        self.label_TitleAjudaLEO.setStyleSheet("QLabel{\n"
"\n"
"color:#010101;\n"
"border:0px;\n"
"font-size:30px;\n"
"font-weight: bold;\n"
"}")
        self.label_TitleAjudaLEO.setObjectName("label_TitleAjudaLEO")
        self.verticalLayout_19.addWidget(self.label_TitleAjudaLEO)
        self.label_SubTitleAjudaLEO2 = QtWidgets.QLabel(self.frame_30)
        self.label_SubTitleAjudaLEO2.setStyleSheet("\n"
"QLabel{\n"
"color:#010101;\n"
"border:0px;\n"
"font-size:19px;\n"
"}")
        self.label_SubTitleAjudaLEO2.setObjectName("label_SubTitleAjudaLEO2")
        self.verticalLayout_19.addWidget(self.label_SubTitleAjudaLEO2)
        self.frame_31 = QtWidgets.QFrame(self.frame_30)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_31)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pushButton_BtnAjuda = QtWidgets.QPushButton(self.frame_31)
        self.pushButton_BtnAjuda.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_BtnAjuda.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_BtnAjuda.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BtnAjuda.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BtnAjuda.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:20px;\n"
"    font-size:15px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}")
        self.pushButton_BtnAjuda.setIcon(icon6)
        self.pushButton_BtnAjuda.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_BtnAjuda.setObjectName("pushButton_BtnAjuda")
        self.horizontalLayout_18.addWidget(self.pushButton_BtnAjuda)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem19)
        self.pushButton_ImgLeo = QtWidgets.QPushButton(self.frame_31)
        self.pushButton_ImgLeo.setMinimumSize(QtCore.QSize(0, 200))
        self.pushButton_ImgLeo.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_ImgLeo.setStyleSheet("QPushButton{ border:0px }")
        self.pushButton_ImgLeo.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/img/leao 1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ImgLeo.setIcon(icon14)
        self.pushButton_ImgLeo.setIconSize(QtCore.QSize(200, 200))
        self.pushButton_ImgLeo.setAutoRepeatDelay(350)
        self.pushButton_ImgLeo.setAutoRepeatInterval(350)
        self.pushButton_ImgLeo.setObjectName("pushButton_ImgLeo")
        self.horizontalLayout_18.addWidget(self.pushButton_ImgLeo)
        self.verticalLayout_19.addWidget(self.frame_31)
        self.verticalLayout_18.addWidget(self.frame_30)
        self.verticalLayout_5.addWidget(self.frame_9)
        self.horizontalLayout_6.addWidget(self.frame_ColumnRight)
        self.verticalLayout.addWidget(self.frame_Central)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Receita Federal"))
        self.pushButton_LogoReceitaFederal.setText(_translate("MainWindow", "Receita Federal"))
        self.textEdit_TxtTopSearch.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:30px; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">O que você precisa?</span></p></body></html>"))
        self.pushButton_TopAlert.setText(_translate("MainWindow", "{0}"))
        self.label_TxtTopDataUser.setText(_translate("MainWindow", "{USER}"))
        self.label_TxtTopDataUserType.setText(_translate("MainWindow", "{PROFILE_TYPE}"))
        self.pushButton_BtnDeclarar.setText(_translate("MainWindow", "   Declarar"))
        self.pushButton_BtnServico.setText(_translate("MainWindow", "Serviços"))
        self.pushButton_BtnAssuntos.setText(_translate("MainWindow", "Assuntos"))
        self.pushButton_BtnAcessoInfo.setText(_translate("MainWindow", "Acesso á Informação"))
        self.pushButton_BtnComposicao.setText(_translate("MainWindow", "Composição"))
        self.pushButton_BtnConsultaProcessos.setText(_translate("MainWindow", "Consultar Processos"))
        self.pushButton_BtnCentraisConteudo.setText(_translate("MainWindow", "Centrais de Conteúdo"))
        self.pushButton_BtnCanaisAtendimento.setText(_translate("MainWindow", "Canais de Atendimento"))
        self.pushButton_BtnOndeEncontro.setText(_translate("MainWindow", "Onde Encontro?"))
        self.pushButton_BtnGovbr.setText(_translate("MainWindow", "gov.br"))
        self.pushButton_BtnConfiguracao.setText(_translate("MainWindow", "   Configurações"))
        self.pushButton_BtnFeedback.setText(_translate("MainWindow", "Feedback"))
        self.pushButton_BtnSugestao.setText(_translate("MainWindow", "Sugestões"))
        self.lineEdit_TxtDataAtual.setText(_translate("MainWindow", "{weekday} 00/00/0000"))
        self.label_TitleDash.setText(_translate("MainWindow", "Acesso Rápido"))
        self.label_SubTitleDash.setText(_translate("MainWindow", "Selecione abaixo o serviço que deseja realizar"))
        self.label_TitleCPF.setText(_translate("MainWindow", "CPF"))
        self.label_SubTitleCPF.setText(_translate("MainWindow", "Cadastro Pessoa Física"))
        self.pushButton_BtnCPF.setText(_translate("MainWindow", "   Acessar"))
        self.label_TitleAlfandega.setText(_translate("MainWindow", "Alfândega"))
        self.label_SubTitleAlfandega.setText(_translate("MainWindow", "e Comércio Exterior"))
        self.pushButton_BtnAlfandega.setText(_translate("MainWindow", "   Acessar"))
        self.label_TitleDeclaracao.setText(_translate("MainWindow", "Declaração de"))
        self.label_SubTitleDeclaracao.setText(_translate("MainWindow", "ajuste anual"))
        self.pushButton_BtnAjusteAnual.setText(_translate("MainWindow", "   Acessar"))
        self.label_TitleImposto.setText(_translate("MainWindow", "Imposto"))
        self.label_SubTitleImposto.setText(_translate("MainWindow", "de renda"))
        self.pushButton_BtnImpostoRenda.setText(_translate("MainWindow", "   Acessar"))
        self.label_11.setText(_translate("MainWindow", "Declaração"))
        self.label_12.setText(_translate("MainWindow", "de importação"))
        self.pushButton_BtnDeclaracaoImport.setText(_translate("MainWindow", "   Acessar"))
        self.label_Restituicao.setText(_translate("MainWindow", "Restituição: "))
        self.label_TxtValorRestituicao.setText(_translate("MainWindow", "R$ 0.000,00"))
        self.pushButton_BtnHistorico.setText(_translate("MainWindow", "Histórico"))
        self.label_TitleCentralAjuda.setText(_translate("MainWindow", "Central de Ajuda"))
        self.pushButton_BtnAjuda01.setText(_translate("MainWindow", "  Como fazer o cálculo do IR"))
        self.pushButton_BtnAjuda02.setText(_translate("MainWindow", "  Quem precisa declarar?"))
        self.pushButton_BtnAjuda03.setText(_translate("MainWindow", "  O que acontece com quem \n"
"  cai na malha fina?"))
        self.pushButton_BtnAjuda04.setText(_translate("MainWindow", "  Quais documentos eu\n"
"  precioso entregar"))
        self.label_RestituicaoIR.setText(_translate("MainWindow", "Restituição do IR"))
        self.label_TitleAjudaLEO.setText(_translate("MainWindow", "<html><head/><body><p>Ainda não encontrou<br/>o que precisava?</p></body></html>"))
        self.label_SubTitleAjudaLEO2.setText(_translate("MainWindow", "<html><head/><body><p>Peça ajuda ao  LEO o <br/>assistente virtual da <br/>Receita Federal</p></body></html>"))
        self.pushButton_BtnAjuda.setText(_translate("MainWindow", "Ajuda  "))
